import { promises as Fs } from 'fs';
import { tmpdir } from 'os';
import * as Path from 'path';
import { compileSchemasFromDirectory, DirectoryGenerationError } from './directory';

describe('compileSchemasFromDirectory', () => {
  let testDirectory: string;

  beforeEach(async () => {
    testDirectory = await Fs.mkdtemp(Path.join(tmpdir(), 'json-schema-to-dts-'));
  });

  afterEach(async () => {
    await Fs.rm(testDirectory, { force: true, recursive: true });
  });

  async function writeSchema(relativePath: string, schema: unknown) {
    const schemaPath = Path.join(testDirectory, 'schemas', relativePath);

    await Fs.mkdir(Path.dirname(schemaPath), { recursive: true });
    await Fs.writeFile(schemaPath, JSON.stringify(schema));

    return schemaPath;
  }

  it('compiles matching schemas to self-contained declaration plans', async () => {
    await writeSchema('shared.schema.json', {
      title: 'Shared',
      type: 'string',
    });
    const rootPath = await writeSchema('nested/root.schema.json', {
      title: 'Root',
      type: 'object',
      properties: {
        value: { $ref: '../shared.schema.json' },
      },
    });
    await writeSchema('ignored.json', { type: 'number' });

    const result = await compileSchemasFromDirectory({
      schemaDirectory: Path.join(testDirectory, 'schemas'),
      outputDirectory: Path.join(testDirectory, 'schemas', 'generated'),
      schemaGlob: '**/*.schema.json',
    });

    expect(result.files).toHaveLength(2);
    expect(result.files.map((file) => file.relativeDeclarationPath)).toEqual([
      'nested/root.schema.d.ts',
      'shared.schema.d.ts',
    ]);

    const rootFile = result.files.find((file) => file.schemaPath === rootPath)!;

    expect(rootFile.typeName).toBe('Root');
    expect(rootFile.text).toContain('// Generated by json-schema-to-dts. Do not edit directly.');
    expect(rootFile.text).toContain('export type Root =');
    expect(rootFile.text).toContain('export type Shared = string;');
  });

  it('rejects a glob that matches no schemas', async () => {
    await writeSchema('root.json', { type: 'string' });

    await expect(
      compileSchemasFromDirectory({
        schemaDirectory: Path.join(testDirectory, 'schemas'),
        outputDirectory: Path.join(testDirectory, 'types'),
        schemaGlob: '*.schema.json',
      }),
    ).rejects.toMatchObject<Partial<DirectoryGenerationError>>({
      issues: [expect.objectContaining({ code: 'ENOMATCH' })],
    });
  });

  it('rejects JSON values that are not schema roots', async () => {
    await writeSchema('root.json', ['not', 'a', 'schema']);

    await expect(
      compileSchemasFromDirectory({
        schemaDirectory: Path.join(testDirectory, 'schemas'),
        outputDirectory: Path.join(testDirectory, 'types'),
      }),
    ).rejects.toMatchObject<Partial<DirectoryGenerationError>>({
      issues: [expect.objectContaining({ code: 'ESCHEMAROOT' })],
    });
  });

  it('rejects glob matches outside the schema directory', async () => {
    await writeSchema('root.json', { type: 'string' });
    await Fs.writeFile(
      Path.join(testDirectory, 'outside.json'),
      JSON.stringify({ type: 'number' }),
    );

    await expect(
      compileSchemasFromDirectory({
        schemaDirectory: Path.join(testDirectory, 'schemas'),
        outputDirectory: Path.join(testDirectory, 'types'),
        schemaGlob: '../outside.json',
      }),
    ).rejects.toMatchObject<Partial<DirectoryGenerationError>>({
      issues: [expect.objectContaining({ code: 'ESCHEMABOUNDARY' })],
    });
  });

  it('rejects unresolved references without producing a plan', async () => {
    await writeSchema('root.json', { $ref: './missing.json' });

    await expect(
      compileSchemasFromDirectory({
        schemaDirectory: Path.join(testDirectory, 'schemas'),
        outputDirectory: Path.join(testDirectory, 'types'),
      }),
    ).rejects.toMatchObject<Partial<DirectoryGenerationError>>({
      issues: [expect.objectContaining({ code: 'EUNRESOLVED' })],
    });
  });

  it('rejects duplicate canonical schema ids', async () => {
    await writeSchema('first.json', { $id: 'https://example.com/shared', type: 'string' });
    await writeSchema('second.json', { $id: 'https://example.com/shared', type: 'number' });

    await expect(
      compileSchemasFromDirectory({
        schemaDirectory: Path.join(testDirectory, 'schemas'),
        outputDirectory: Path.join(testDirectory, 'types'),
      }),
    ).rejects.toMatchObject<Partial<DirectoryGenerationError>>({
      issues: [expect.objectContaining({ code: 'EDUPLICATEID' })],
    });
  });
});
