import { promises as Fs } from 'fs';
import { tmpdir } from 'os';
import * as Path from 'path';
import {
  compileSchemasFromDirectory,
  DirectoryGenerationError,
  generateTypesFromDirectory,
} from './directory';

describe('compileSchemasFromDirectory', () => {
  let testDirectory: string;

  beforeEach(async () => {
    testDirectory = await Fs.mkdtemp(Path.join(tmpdir(), 'json-schema-to-dts-'));
  });

  afterEach(async () => {
    await Fs.rm(testDirectory, { force: true, recursive: true });
  });

  async function writeSchema(relativePath: string, schema: unknown) {
    const schemaPath = Path.join(testDirectory, 'schemas', relativePath);

    await Fs.mkdir(Path.dirname(schemaPath), { recursive: true });
    await Fs.writeFile(schemaPath, JSON.stringify(schema));

    return schemaPath;
  }

  it('compiles matching schemas to self-contained declaration plans', async () => {
    await writeSchema('shared.schema.json', {
      title: 'Shared',
      type: 'string',
    });
    const rootPath = await writeSchema('nested/root.schema.json', {
      title: 'Root',
      type: 'object',
      properties: {
        value: { $ref: '../shared.schema.json' },
      },
    });
    await writeSchema('ignored.json', { type: 'number' });

    const result = await compileSchemasFromDirectory({
      schemaDirectory: Path.join(testDirectory, 'schemas'),
      outputDirectory: Path.join(testDirectory, 'schemas', 'generated'),
      schemaGlob: '**/*.schema.json',
    });

    expect(result.files).toHaveLength(2);
    expect(result.files.map((file) => file.relativeDeclarationPath)).toEqual([
      'nested/root.schema.d.ts',
      'shared.schema.d.ts',
    ]);

    const rootFile = result.files.find((file) => file.schemaPath === rootPath)!;

    expect(rootFile.typeName).toBe('Root');
    expect(rootFile.text).toContain('// Generated by json-schema-to-dts. Do not edit directly.');
    expect(rootFile.text).toContain('export type Root =');
    expect(rootFile.text).toContain('export type Shared = string;');
  });

  it('rejects a glob that matches no schemas', async () => {
    await writeSchema('root.json', { type: 'string' });

    await expect(
      compileSchemasFromDirectory({
        schemaDirectory: Path.join(testDirectory, 'schemas'),
        outputDirectory: Path.join(testDirectory, 'types'),
        schemaGlob: '*.schema.json',
      }),
    ).rejects.toMatchObject<Partial<DirectoryGenerationError>>({
      issues: [expect.objectContaining({ code: 'ENOMATCH' })],
    });
  });

  it('rejects JSON values that are not schema roots', async () => {
    await writeSchema('root.json', ['not', 'a', 'schema']);

    await expect(
      compileSchemasFromDirectory({
        schemaDirectory: Path.join(testDirectory, 'schemas'),
        outputDirectory: Path.join(testDirectory, 'types'),
      }),
    ).rejects.toMatchObject<Partial<DirectoryGenerationError>>({
      issues: [expect.objectContaining({ code: 'ESCHEMAROOT' })],
    });
  });

  it('rejects glob matches outside the schema directory', async () => {
    await writeSchema('root.json', { type: 'string' });
    await Fs.writeFile(
      Path.join(testDirectory, 'outside.json'),
      JSON.stringify({ type: 'number' }),
    );

    await expect(
      compileSchemasFromDirectory({
        schemaDirectory: Path.join(testDirectory, 'schemas'),
        outputDirectory: Path.join(testDirectory, 'types'),
        schemaGlob: '../outside.json',
      }),
    ).rejects.toMatchObject<Partial<DirectoryGenerationError>>({
      issues: [expect.objectContaining({ code: 'ESCHEMABOUNDARY' })],
    });
  });

  it('rejects unresolved references without producing a plan', async () => {
    await writeSchema('root.json', { $ref: './missing.json' });

    await expect(
      compileSchemasFromDirectory({
        schemaDirectory: Path.join(testDirectory, 'schemas'),
        outputDirectory: Path.join(testDirectory, 'types'),
      }),
    ).rejects.toMatchObject<Partial<DirectoryGenerationError>>({
      issues: [expect.objectContaining({ code: 'EUNRESOLVED' })],
    });
  });

  it('rejects duplicate canonical schema ids', async () => {
    await writeSchema('first.json', { $id: 'https://example.com/shared', type: 'string' });
    await writeSchema('second.json', { $id: 'https://example.com/shared', type: 'number' });

    await expect(
      compileSchemasFromDirectory({
        schemaDirectory: Path.join(testDirectory, 'schemas'),
        outputDirectory: Path.join(testDirectory, 'types'),
      }),
    ).rejects.toMatchObject<Partial<DirectoryGenerationError>>({
      issues: [expect.objectContaining({ code: 'EDUPLICATEID' })],
    });
  });

  it('writes declarations and skips unchanged files on later runs', async () => {
    const schemaPath = await writeSchema('nested/root.schema.json', {
      title: 'Root',
      type: 'string',
    });
    const outputDirectory = Path.join(testDirectory, 'types');
    const options = {
      schemaDirectory: Path.join(testDirectory, 'schemas'),
      outputDirectory,
      schemaGlob: '**/*.schema.json',
    };

    const firstResult = await generateTypesFromDirectory(options);
    const declarationPath = Path.join(outputDirectory, 'nested', 'root.schema.d.ts');

    expect(firstResult).toMatchObject({
      files: [
        {
          schemaPath,
          declarationPath,
          typeName: 'Root',
          status: 'created',
        },
      ],
      diagnostics: [],
      removedFiles: [],
    });
    await expect(Fs.readFile(declarationPath, 'utf8')).resolves.toContain(
      'export type Root = string;',
    );

    const firstStats = await Fs.stat(declarationPath);
    const secondResult = await generateTypesFromDirectory(options);
    const secondStats = await Fs.stat(declarationPath);

    expect(secondResult.files[0].status).toBe('unchanged');
    expect(secondStats.mtimeMs).toBe(firstStats.mtimeMs);

    await Fs.writeFile(declarationPath, 'manually changed');

    const thirdResult = await generateTypesFromDirectory(options);

    expect(thirdResult.files[0].status).toBe('updated');
    await expect(Fs.readFile(declarationPath, 'utf8')).resolves.toContain(
      'export type Root = string;',
    );
  });

  it('rejects untracked output collisions before writing', async () => {
    await writeSchema('root.json', { type: 'string' });
    const outputDirectory = Path.join(testDirectory, 'types');
    const declarationPath = Path.join(outputDirectory, 'root.d.ts');

    await Fs.mkdir(outputDirectory, { recursive: true });
    await Fs.writeFile(declarationPath, 'export type Handwritten = true;\n');

    await expect(
      generateTypesFromDirectory({
        schemaDirectory: Path.join(testDirectory, 'schemas'),
        outputDirectory,
      }),
    ).rejects.toMatchObject<Partial<DirectoryGenerationError>>({
      issues: [expect.objectContaining({ code: 'EOUTPUTCOLLISION' })],
    });
    await expect(Fs.readFile(declarationPath, 'utf8')).resolves.toBe(
      'export type Handwritten = true;\n',
    );
    await expect(
      Fs.access(Path.join(outputDirectory, '.json-schema-to-dts-manifest.json')),
    ).rejects.toMatchObject({ code: 'ENOENT' });
  });

  it('does not touch the output directory when compilation fails', async () => {
    await writeSchema('root.json', { $ref: './missing.json' });
    const outputDirectory = Path.join(testDirectory, 'types');
    const unrelatedPath = Path.join(outputDirectory, 'handwritten.d.ts');

    await Fs.mkdir(outputDirectory, { recursive: true });
    await Fs.writeFile(unrelatedPath, 'unchanged');

    await expect(
      generateTypesFromDirectory({
        schemaDirectory: Path.join(testDirectory, 'schemas'),
        outputDirectory,
      }),
    ).rejects.toBeInstanceOf(DirectoryGenerationError);
    await expect(Fs.readFile(unrelatedPath, 'utf8')).resolves.toBe('unchanged');
    await expect(Fs.readdir(outputDirectory)).resolves.toEqual(['handwritten.d.ts']);
  });
});
