import { promises as Fs } from 'fs';
import * as Path from 'path';
import { fileURLToPath, pathToFileURL } from 'url';
import fastGlob from 'fast-glob';
import { IParserDiagnostic, ParserDiagnosticKind } from './diagnostics';
import { Parser, ParserCompileOptions, ParserOptions } from './parser';
import { JSONSchema7Definition } from './types';

const GENERATED_FILE_HEADER = '// Generated by json-schema-to-dts. Do not edit directly.\n\n';

export interface DirectoryGenerationOptions {
  schemaDirectory: string;
  outputDirectory: string;
  schemaGlob?: string | string[];
  parserOptions?: ParserOptions;
  compileOptions?: ParserCompileOptions;
}

export interface DirectoryGenerationIssue {
  code: string;
  message: string;
  schemaPath?: string;
  declarationPath?: string;
  diagnostic?: IParserDiagnostic;
}

export class DirectoryGenerationError extends Error {
  readonly issues: DirectoryGenerationIssue[];

  constructor(issues: DirectoryGenerationIssue[]) {
    super(issues.map((issue) => issue.message).join('\n'));
    this.name = 'DirectoryGenerationError';
    this.issues = issues;
  }
}

export interface CompiledDirectoryFile {
  schemaPath: string;
  declarationPath: string;
  relativeDeclarationPath: string;
  typeName: string;
  text: string;
}

export interface DirectoryCompilation {
  files: CompiledDirectoryFile[];
  diagnostics: IParserDiagnostic[];
}

interface LoadedSchema {
  schemaPath: string;
  relativeSchemaPath: string;
  uri: string;
  schema: JSONSchema7Definition;
}

export async function compileSchemasFromDirectory(
  options: DirectoryGenerationOptions,
): Promise<DirectoryCompilation> {
  const schemaDirectory = Path.resolve(options.schemaDirectory);
  const outputDirectory = Path.resolve(options.outputDirectory);
  const directoryIssues = await validateDirectories(schemaDirectory, outputDirectory);

  if (directoryIssues.length) {
    throw new DirectoryGenerationError(directoryIssues);
  }

  const relativeOutputDirectory = Path.relative(schemaDirectory, outputDirectory);
  const ignore = isPathWithin(relativeOutputDirectory)
    ? [`${toPosixPath(relativeOutputDirectory)}/**`]
    : [];
  const schemaGlob = options.schemaGlob ?? '**/*.json';
  let relativeSchemaPaths: string[];

  try {
    relativeSchemaPaths = await fastGlob(schemaGlob, {
      cwd: schemaDirectory,
      dot: false,
      followSymbolicLinks: false,
      ignore,
      onlyFiles: true,
      unique: true,
    });
  } catch (error) {
    throw new DirectoryGenerationError([
      {
        code: 'EGLOB',
        message: `Unable to discover schemas in ${JSON.stringify(schemaDirectory)}: ${getErrorMessage(
          error,
        )}`,
      },
    ]);
  }

  relativeSchemaPaths = [...new Set(relativeSchemaPaths.map(toPosixPath))].sort();

  const outsideSchemaPaths = relativeSchemaPaths.filter(
    (relativeSchemaPath) => !isPathWithin(relativeSchemaPath),
  );

  if (outsideSchemaPaths.length) {
    throw new DirectoryGenerationError(
      outsideSchemaPaths.map((relativeSchemaPath) => ({
        code: 'ESCHEMABOUNDARY',
        message: `Matched schema path ${JSON.stringify(
          relativeSchemaPath,
        )} is outside the schema directory.`,
        schemaPath: Path.resolve(schemaDirectory, relativeSchemaPath),
      })),
    );
  }

  if (!relativeSchemaPaths.length) {
    throw new DirectoryGenerationError([
      {
        code: 'ENOMATCH',
        message: `No schemas matched ${JSON.stringify(schemaGlob)} in ${JSON.stringify(
          schemaDirectory,
        )}.`,
      },
    ]);
  }

  const loadedSchemas = await loadSchemas(schemaDirectory, relativeSchemaPaths);
  const compiledFiles: CompiledDirectoryFile[] = [];
  const diagnostics = new Map<string, IParserDiagnostic>();
  const compileIssues: DirectoryGenerationIssue[] = [];

  for (const rootSchema of loadedSchemas) {
    const parser = new Parser(options.parserOptions);
    const schemasInRegistrationOrder = [
      rootSchema,
      ...loadedSchemas.filter((schema) => schema !== rootSchema),
    ];
    let typeName = '';

    try {
      for (const schema of schemasInRegistrationOrder) {
        const registeredName = parser.addSchema(schema.uri, schema.schema, {
          isRoot: schema === rootSchema,
        });

        if (schema === rootSchema) {
          typeName = registeredName;
        }
      }

      const compiled = parser.compile(options.compileOptions);

      for (const diagnostic of compiled.diagnostics) {
        diagnostics.set(diagnosticKey(diagnostic), diagnostic);
      }

      const relativeDeclarationPath = rootSchema.relativeSchemaPath.replace(/\.json$/, '.d.ts');

      compiledFiles.push({
        schemaPath: rootSchema.schemaPath,
        declarationPath: Path.resolve(outputDirectory, relativeDeclarationPath),
        relativeDeclarationPath,
        typeName,
        text: `${GENERATED_FILE_HEADER}${compiled.text}`,
      });
    } catch (error) {
      compileIssues.push({
        code: 'ECOMPILE',
        message: `Unable to compile ${JSON.stringify(rootSchema.schemaPath)}: ${getErrorMessage(
          error,
        )}`,
        schemaPath: rootSchema.schemaPath,
      });
    }
  }

  const uniqueDiagnostics = [...diagnostics.values()];

  for (const diagnostic of uniqueDiagnostics) {
    if (diagnostic.severity === ParserDiagnosticKind.Error) {
      compileIssues.push({
        code: diagnostic.code,
        message: diagnostic.message,
        schemaPath: uriToSchemaPath(diagnostic.uri),
        diagnostic,
      });
    }
  }

  if (compileIssues.length) {
    throw new DirectoryGenerationError(deduplicateIssues(compileIssues));
  }

  return {
    files: compiledFiles,
    diagnostics: uniqueDiagnostics,
  };
}

async function validateDirectories(
  schemaDirectory: string,
  outputDirectory: string,
): Promise<DirectoryGenerationIssue[]> {
  if (schemaDirectory === outputDirectory) {
    return [
      {
        code: 'EDIRECTORYOVERLAP',
        message: 'The schema and output directories must not be the same directory.',
      },
    ];
  }

  try {
    const stats = await Fs.stat(schemaDirectory);

    if (!stats.isDirectory()) {
      return [
        {
          code: 'ESCHEMADIRECTORY',
          message: `The schema path ${JSON.stringify(schemaDirectory)} is not a directory.`,
        },
      ];
    }
  } catch (error) {
    return [
      {
        code: 'ESCHEMADIRECTORY',
        message: `Unable to access schema directory ${JSON.stringify(
          schemaDirectory,
        )}: ${getErrorMessage(error)}`,
      },
    ];
  }

  return [];
}

async function loadSchemas(
  schemaDirectory: string,
  relativeSchemaPaths: string[],
): Promise<LoadedSchema[]> {
  const schemas: LoadedSchema[] = [];
  const issues: DirectoryGenerationIssue[] = [];

  for (const relativeSchemaPath of relativeSchemaPaths) {
    const schemaPath = Path.resolve(schemaDirectory, relativeSchemaPath);

    if (!relativeSchemaPath.endsWith('.json')) {
      issues.push({
        code: 'EEXTENSION',
        message: `Matched schema ${JSON.stringify(schemaPath)} does not end in .json.`,
        schemaPath,
      });
      continue;
    }

    try {
      const stats = await Fs.lstat(schemaPath);

      if (stats.isSymbolicLink()) {
        continue;
      }

      const source = await Fs.readFile(schemaPath, 'utf8');
      let schema: unknown;

      try {
        schema = JSON.parse(source);
      } catch (error) {
        issues.push({
          code: 'EINVALIDJSON',
          message: `Unable to parse schema ${JSON.stringify(schemaPath)}: ${getErrorMessage(error)}`,
          schemaPath,
        });
        continue;
      }

      if (!isSchemaRoot(schema)) {
        issues.push({
          code: 'ESCHEMAROOT',
          message: `Schema ${JSON.stringify(schemaPath)} must contain a JSON object or boolean.`,
          schemaPath,
        });
        continue;
      }

      schemas.push({
        schemaPath,
        relativeSchemaPath,
        schema,
        uri: pathToFileURL(schemaPath).href,
      });
    } catch (error) {
      issues.push({
        code: 'ESCHEMAREAD',
        message: `Unable to read schema ${JSON.stringify(schemaPath)}: ${getErrorMessage(error)}`,
        schemaPath,
      });
    }
  }

  if (issues.length) {
    throw new DirectoryGenerationError(issues);
  }

  if (!schemas.length) {
    throw new DirectoryGenerationError([
      {
        code: 'ENOMATCH',
        message: 'No non-symbolic-link schema files remained after discovery.',
      },
    ]);
  }

  return schemas;
}

function isSchemaRoot(value: unknown): value is JSONSchema7Definition {
  return (
    typeof value === 'boolean' ||
    (typeof value === 'object' && value !== null && !Array.isArray(value))
  );
}

function isPathWithin(relativePath: string) {
  return (
    !!relativePath &&
    relativePath !== '..' &&
    !relativePath.startsWith(`..${Path.sep}`) &&
    !Path.isAbsolute(relativePath)
  );
}

function toPosixPath(value: string) {
  return value.split(Path.sep).join('/');
}

function diagnosticKey(diagnostic: IParserDiagnostic) {
  return [
    diagnostic.code,
    diagnostic.severity,
    diagnostic.uri,
    diagnostic.baseUri,
    diagnostic.message,
  ].join('\u0000');
}

function deduplicateIssues(issues: DirectoryGenerationIssue[]) {
  const uniqueIssues = new Map<string, DirectoryGenerationIssue>();

  for (const issue of issues) {
    const key = issue.diagnostic
      ? [issue.code, issue.diagnostic.baseUri].join('\u0000')
      : [issue.code, issue.schemaPath, issue.declarationPath, issue.message].join('\u0000');

    uniqueIssues.set(key, issue);
  }

  return [...uniqueIssues.values()];
}

function uriToSchemaPath(uri: string) {
  try {
    const url = new URL(uri);

    return url.protocol === 'file:' ? fileURLToPath(url) : undefined;
  } catch {
    return undefined;
  }
}

function getErrorMessage(error: unknown) {
  return error instanceof Error ? error.message : String(error);
}
