import { promises as Fs } from 'fs';
import * as Path from 'path';
import { fileURLToPath, pathToFileURL } from 'url';
import { randomUUID } from 'crypto';
import fastGlob from 'fast-glob';
import { IParserDiagnostic, ParserDiagnosticKind } from './diagnostics';
import { Parser, ParserCompileOptions, ParserOptions } from './parser';
import { JSONSchema7Definition } from './types';

const GENERATED_FILE_HEADER = '// Generated by json-schema-to-dts. Do not edit directly.\n\n';
const MANIFEST_FILE_NAME = '.json-schema-to-dts-manifest.json';
const MANIFEST_VERSION = 1;

export type GeneratedDeclarationStatus = 'created' | 'updated' | 'unchanged';

export interface DirectoryGenerationOptions {
  schemaDirectory: string;
  outputDirectory: string;
  schemaGlob?: string | string[];
  parserOptions?: ParserOptions;
  compileOptions?: ParserCompileOptions;
}

export interface DirectoryGenerationIssue {
  code: string;
  message: string;
  schemaPath?: string;
  declarationPath?: string;
  diagnostic?: IParserDiagnostic;
}

export class DirectoryGenerationError extends Error {
  readonly issues: DirectoryGenerationIssue[];

  constructor(issues: DirectoryGenerationIssue[]) {
    super(issues.map((issue) => issue.message).join('\n'));
    this.name = 'DirectoryGenerationError';
    this.issues = issues;
  }
}

export interface CompiledDirectoryFile {
  schemaPath: string;
  relativeSchemaPath: string;
  declarationPath: string;
  relativeDeclarationPath: string;
  typeName: string;
  text: string;
}

export interface DirectoryCompilation {
  files: CompiledDirectoryFile[];
  diagnostics: IParserDiagnostic[];
}

export interface GeneratedDeclarationFile {
  schemaPath: string;
  declarationPath: string;
  typeName: string;
  status: GeneratedDeclarationStatus;
}

export interface DirectoryGenerationResult {
  files: GeneratedDeclarationFile[];
  diagnostics: IParserDiagnostic[];
  removedFiles: string[];
}

interface ManifestFile {
  schemaPath: string;
  declarationPath: string;
}

interface GenerationManifest {
  version: 1;
  state: 'complete' | 'pending';
  files: ManifestFile[];
  previousFiles?: ManifestFile[];
}

interface PlannedWrite extends CompiledDirectoryFile {
  status: GeneratedDeclarationStatus;
}

interface LoadedSchema {
  schemaPath: string;
  relativeSchemaPath: string;
  uri: string;
  schema: JSONSchema7Definition;
}

export async function compileSchemasFromDirectory(
  options: DirectoryGenerationOptions,
): Promise<DirectoryCompilation> {
  const schemaDirectory = Path.resolve(options.schemaDirectory);
  const outputDirectory = Path.resolve(options.outputDirectory);
  const directoryIssues = await validateDirectories(schemaDirectory, outputDirectory);

  if (directoryIssues.length) {
    throw new DirectoryGenerationError(directoryIssues);
  }

  const relativeOutputDirectory = Path.relative(schemaDirectory, outputDirectory);
  const ignore = isPathWithin(relativeOutputDirectory)
    ? [`${toPosixPath(relativeOutputDirectory)}/**`]
    : [];
  const schemaGlob = options.schemaGlob ?? '**/*.json';
  let relativeSchemaPaths: string[];

  try {
    relativeSchemaPaths = await fastGlob(schemaGlob, {
      cwd: schemaDirectory,
      dot: false,
      followSymbolicLinks: false,
      ignore,
      onlyFiles: true,
      unique: true,
    });
  } catch (error) {
    throw new DirectoryGenerationError([
      {
        code: 'EGLOB',
        message: `Unable to discover schemas in ${JSON.stringify(schemaDirectory)}: ${getErrorMessage(
          error,
        )}`,
      },
    ]);
  }

  relativeSchemaPaths = [...new Set(relativeSchemaPaths.map(toPosixPath))].sort();

  const outsideSchemaPaths = relativeSchemaPaths.filter(
    (relativeSchemaPath) => !isPathWithin(relativeSchemaPath),
  );

  if (outsideSchemaPaths.length) {
    throw new DirectoryGenerationError(
      outsideSchemaPaths.map((relativeSchemaPath) => ({
        code: 'ESCHEMABOUNDARY',
        message: `Matched schema path ${JSON.stringify(
          relativeSchemaPath,
        )} is outside the schema directory.`,
        schemaPath: Path.resolve(schemaDirectory, relativeSchemaPath),
      })),
    );
  }

  if (!relativeSchemaPaths.length) {
    throw new DirectoryGenerationError([
      {
        code: 'ENOMATCH',
        message: `No schemas matched ${JSON.stringify(schemaGlob)} in ${JSON.stringify(
          schemaDirectory,
        )}.`,
      },
    ]);
  }

  const loadedSchemas = await loadSchemas(schemaDirectory, relativeSchemaPaths);
  const compiledFiles: CompiledDirectoryFile[] = [];
  const diagnostics = new Map<string, IParserDiagnostic>();
  const compileIssues: DirectoryGenerationIssue[] = [];

  for (const rootSchema of loadedSchemas) {
    const parser = new Parser(options.parserOptions);
    const schemasInRegistrationOrder = [
      rootSchema,
      ...loadedSchemas.filter((schema) => schema !== rootSchema),
    ];
    let typeName = '';

    try {
      for (const schema of schemasInRegistrationOrder) {
        const registeredName = parser.addSchema(schema.uri, schema.schema, {
          isRoot: schema === rootSchema,
        });

        if (schema === rootSchema) {
          typeName = registeredName;
        }
      }

      const compiled = parser.compile(options.compileOptions);

      for (const diagnostic of compiled.diagnostics) {
        diagnostics.set(diagnosticKey(diagnostic), diagnostic);
      }

      const relativeDeclarationPath = rootSchema.relativeSchemaPath.replace(/\.json$/, '.d.ts');

      compiledFiles.push({
        schemaPath: rootSchema.schemaPath,
        relativeSchemaPath: rootSchema.relativeSchemaPath,
        declarationPath: Path.resolve(outputDirectory, relativeDeclarationPath),
        relativeDeclarationPath,
        typeName,
        text: `${GENERATED_FILE_HEADER}${compiled.text}`,
      });
    } catch (error) {
      compileIssues.push({
        code: 'ECOMPILE',
        message: `Unable to compile ${JSON.stringify(rootSchema.schemaPath)}: ${getErrorMessage(
          error,
        )}`,
        schemaPath: rootSchema.schemaPath,
      });
    }
  }

  const uniqueDiagnostics = [...diagnostics.values()];

  for (const diagnostic of uniqueDiagnostics) {
    if (diagnostic.severity === ParserDiagnosticKind.Error) {
      compileIssues.push({
        code: diagnostic.code,
        message: diagnostic.message,
        schemaPath: uriToSchemaPath(diagnostic.uri),
        diagnostic,
      });
    }
  }

  if (compileIssues.length) {
    throw new DirectoryGenerationError(deduplicateIssues(compileIssues));
  }

  return {
    files: compiledFiles,
    diagnostics: uniqueDiagnostics,
  };
}

export async function generateTypesFromDirectory(
  options: DirectoryGenerationOptions,
): Promise<DirectoryGenerationResult> {
  const compilation = await compileSchemasFromDirectory(options);
  const outputDirectory = Path.resolve(options.outputDirectory);
  const manifestPath = Path.join(outputDirectory, MANIFEST_FILE_NAME);
  const previousManifest = await readManifest(manifestPath, outputDirectory);
  const previousFiles = previousManifest?.files ?? [];
  const previouslyOwnedFiles = [
    ...previousFiles,
    ...(previousManifest?.state === 'pending' ? previousManifest.previousFiles ?? [] : []),
  ];
  const ownedDeclarationPaths = new Set(
    previouslyOwnedFiles.map((file) => normalizedPathKey(file.declarationPath)),
  );
  const previousFileBySchemaPath = new Map(
    previousFiles.map((file) => [file.schemaPath, file] as const),
  );
  const plannedWrites: PlannedWrite[] = [];
  const assignedDeclarationPaths = new Set<string>();
  const collisionIssues: DirectoryGenerationIssue[] = [];
  const filesWithExistingMappings = compilation.files.filter((file) =>
    previousFileBySchemaPath.has(file.relativeSchemaPath),
  );
  const filesWithoutExistingMappings = compilation.files.filter(
    (file) => !previousFileBySchemaPath.has(file.relativeSchemaPath),
  );

  for (const file of [...filesWithExistingMappings, ...filesWithoutExistingMappings]) {
    const previousFile = previousFileBySchemaPath.get(file.relativeSchemaPath);
    const preferredRelativePath = previousFile?.declarationPath ?? file.relativeDeclarationPath;
    const resolved = await resolveDeclarationPath({
      outputDirectory,
      relativeDeclarationPath: preferredRelativePath,
      assignedDeclarationPaths,
      ownedDeclarationPaths,
      schemaPath: file.schemaPath,
    });

    if (resolved.issue) {
      collisionIssues.push(resolved.issue);
      continue;
    }

    const declarationPath = Path.resolve(outputDirectory, resolved.relativeDeclarationPath);
    const existingText = await readExistingOutput(
      declarationPath,
      ownedDeclarationPaths.has(normalizedPathKey(resolved.relativeDeclarationPath)),
    );

    if (existingText.issue) {
      collisionIssues.push(existingText.issue);
      continue;
    }

    plannedWrites.push({
      ...file,
      declarationPath,
      relativeDeclarationPath: resolved.relativeDeclarationPath,
      status:
        typeof existingText.text === 'undefined'
          ? 'created'
          : existingText.text === file.text
            ? 'unchanged'
            : 'updated',
    });
  }

  if (collisionIssues.length) {
    throw new DirectoryGenerationError(collisionIssues);
  }

  plannedWrites.sort((left, right) => left.schemaPath.localeCompare(right.schemaPath));

  const manifestFiles = plannedWrites.map((file) => ({
    schemaPath: file.relativeSchemaPath,
    declarationPath: file.relativeDeclarationPath,
  }));
  const currentDeclarationPaths = new Set(
    manifestFiles.map((file) => normalizedPathKey(file.declarationPath)),
  );
  const staleFiles = deduplicateManifestFiles(previouslyOwnedFiles).filter(
    (file) => !currentDeclarationPaths.has(normalizedPathKey(file.declarationPath)),
  );
  const completeManifest: GenerationManifest = {
    version: MANIFEST_VERSION,
    state: 'complete',
    files: manifestFiles,
  };
  const changedWrites = plannedWrites.filter((file) => file.status !== 'unchanged');
  const manifestIsCurrent =
    previousManifest?.state === 'complete' &&
    JSON.stringify(previousManifest) === JSON.stringify(completeManifest);

  if (!changedWrites.length && !staleFiles.length && manifestIsCurrent) {
    return toGenerationResult(plannedWrites, compilation.diagnostics, []);
  }

  const pendingManifest: GenerationManifest = {
    ...completeManifest,
    state: 'pending',
    previousFiles: deduplicateManifestFiles(previouslyOwnedFiles),
  };

  try {
    await Fs.mkdir(outputDirectory, { recursive: true });
    await writeFileAtomically(manifestPath, formatManifest(pendingManifest));

    for (const file of changedWrites) {
      await Fs.mkdir(Path.dirname(file.declarationPath), { recursive: true });
      await writeFileAtomically(file.declarationPath, file.text);
    }

    const removedFiles: string[] = [];

    for (const staleFile of staleFiles) {
      const stalePath = Path.resolve(outputDirectory, staleFile.declarationPath);

      try {
        await Fs.unlink(stalePath);
        removedFiles.push(stalePath);
      } catch (error) {
        if (!isNodeError(error, 'ENOENT')) {
          throw error;
        }
      }
    }

    await writeFileAtomically(manifestPath, formatManifest(completeManifest));

    return toGenerationResult(plannedWrites, compilation.diagnostics, removedFiles);
  } catch (error) {
    if (error instanceof DirectoryGenerationError) {
      throw error;
    }

    throw new DirectoryGenerationError([
      {
        code: 'EOUTPUTWRITE',
        message: `Unable to update declarations in ${JSON.stringify(
          outputDirectory,
        )}: ${getErrorMessage(error)}`,
      },
    ]);
  }
}

async function readManifest(
  manifestPath: string,
  outputDirectory: string,
): Promise<GenerationManifest | undefined> {
  let source: string;

  try {
    source = await Fs.readFile(manifestPath, 'utf8');
  } catch (error) {
    if (isNodeError(error, 'ENOENT')) {
      return;
    }

    throw new DirectoryGenerationError([
      {
        code: 'EMANIFEST',
        message: `Unable to read generation manifest ${JSON.stringify(
          manifestPath,
        )}: ${getErrorMessage(error)}`,
      },
    ]);
  }

  try {
    const manifest = JSON.parse(source) as unknown;

    if (!isGenerationManifest(manifest)) {
      throw new Error('The manifest has an unsupported or invalid structure.');
    }

    for (const file of [...manifest.files, ...(manifest.previousFiles ?? [])]) {
      if (!isSafeRelativePath(file.schemaPath) || !isSafeDeclarationPath(file.declarationPath)) {
        throw new Error('The manifest contains a path outside its configured directories.');
      }

      const declarationPath = Path.resolve(outputDirectory, file.declarationPath);

      if (!isPathWithin(Path.relative(outputDirectory, declarationPath))) {
        throw new Error('The manifest contains a declaration outside the output directory.');
      }
    }

    return manifest;
  } catch (error) {
    throw new DirectoryGenerationError([
      {
        code: 'EMANIFEST',
        message: `Unable to use generation manifest ${JSON.stringify(
          manifestPath,
        )}: ${getErrorMessage(error)}`,
      },
    ]);
  }
}

function isGenerationManifest(value: unknown): value is GenerationManifest {
  if (typeof value !== 'object' || value === null) {
    return false;
  }

  const manifest = value as Partial<GenerationManifest>;

  return (
    manifest.version === MANIFEST_VERSION &&
    (manifest.state === 'complete' || manifest.state === 'pending') &&
    Array.isArray(manifest.files) &&
    manifest.files.every(isManifestFile) &&
    (typeof manifest.previousFiles === 'undefined' ||
      (Array.isArray(manifest.previousFiles) && manifest.previousFiles.every(isManifestFile)))
  );
}

function isManifestFile(value: unknown): value is ManifestFile {
  return (
    typeof value === 'object' &&
    value !== null &&
    typeof (value as ManifestFile).schemaPath === 'string' &&
    typeof (value as ManifestFile).declarationPath === 'string'
  );
}

async function resolveDeclarationPath(options: {
  outputDirectory: string;
  relativeDeclarationPath: string;
  assignedDeclarationPaths: Set<string>;
  ownedDeclarationPaths: Set<string>;
  schemaPath: string;
}): Promise<{ relativeDeclarationPath: string; issue?: DirectoryGenerationIssue }> {
  const pathKey = normalizedPathKey(options.relativeDeclarationPath);
  const declarationPath = Path.resolve(options.outputDirectory, options.relativeDeclarationPath);
  const isAssigned = options.assignedDeclarationPaths.has(pathKey);
  const isOwned = options.ownedDeclarationPaths.has(pathKey);
  const exists = await pathExists(declarationPath);

  if (!isAssigned && (!exists || isOwned)) {
    options.assignedDeclarationPaths.add(pathKey);
    return { relativeDeclarationPath: options.relativeDeclarationPath };
  }

  return {
    relativeDeclarationPath: options.relativeDeclarationPath,
    issue: {
      code: 'EOUTPUTCOLLISION',
      message: `Declaration path ${JSON.stringify(
        declarationPath,
      )} is already occupied by an untracked file or another schema.`,
      schemaPath: options.schemaPath,
      declarationPath,
    },
  };
}

async function readExistingOutput(
  declarationPath: string,
  isOwned: boolean,
): Promise<{ text?: string; issue?: DirectoryGenerationIssue }> {
  try {
    const text = await Fs.readFile(declarationPath, 'utf8');

    if (!isOwned) {
      return {
        issue: {
          code: 'EOUTPUTCOLLISION',
          message: `Declaration path ${JSON.stringify(declarationPath)} is not manifest-owned.`,
          declarationPath,
        },
      };
    }

    return { text };
  } catch (error) {
    if (isNodeError(error, 'ENOENT')) {
      return {};
    }

    return {
      issue: {
        code: 'EOUTPUTREAD',
        message: `Unable to inspect declaration ${JSON.stringify(
          declarationPath,
        )}: ${getErrorMessage(error)}`,
        declarationPath,
      },
    };
  }
}

async function pathExists(path: string) {
  try {
    await Fs.access(path);
    return true;
  } catch (error) {
    if (isNodeError(error, 'ENOENT')) {
      return false;
    }

    throw new DirectoryGenerationError([
      {
        code: 'EOUTPUTREAD',
        message: `Unable to inspect output path ${JSON.stringify(path)}: ${getErrorMessage(error)}`,
        declarationPath: path,
      },
    ]);
  }
}

async function writeFileAtomically(path: string, contents: string) {
  const temporaryPath = Path.join(
    Path.dirname(path),
    `.${Path.basename(path)}.${process.pid}.${randomUUID()}.tmp`,
  );

  try {
    await Fs.writeFile(temporaryPath, contents);
    await Fs.rename(temporaryPath, path);
  } finally {
    try {
      await Fs.unlink(temporaryPath);
    } catch (error) {
      if (!isNodeError(error, 'ENOENT')) {
        throw error;
      }
    }
  }
}

function isSafeRelativePath(path: string) {
  return isPathWithin(path) && !Path.isAbsolute(path);
}

function isSafeDeclarationPath(path: string) {
  return isSafeRelativePath(path) && path.endsWith('.d.ts');
}

function normalizedPathKey(path: string) {
  return toPosixPath(path).toLowerCase();
}

function deduplicateManifestFiles(files: ManifestFile[]) {
  const uniqueFiles = new Map<string, ManifestFile>();

  for (const file of files) {
    uniqueFiles.set(normalizedPathKey(file.declarationPath), file);
  }

  return [...uniqueFiles.values()];
}

function formatManifest(manifest: GenerationManifest) {
  return `${JSON.stringify(manifest, null, 2)}\n`;
}

function toGenerationResult(
  files: PlannedWrite[],
  diagnostics: IParserDiagnostic[],
  removedFiles: string[],
): DirectoryGenerationResult {
  return {
    files: files.map((file) => ({
      schemaPath: file.schemaPath,
      declarationPath: file.declarationPath,
      typeName: file.typeName,
      status: file.status,
    })),
    diagnostics,
    removedFiles,
  };
}

function isNodeError(error: unknown, code: string): error is NodeJS.ErrnoException {
  return (
    typeof error === 'object' && error !== null && (error as NodeJS.ErrnoException).code === code
  );
}

async function validateDirectories(
  schemaDirectory: string,
  outputDirectory: string,
): Promise<DirectoryGenerationIssue[]> {
  if (schemaDirectory === outputDirectory) {
    return [
      {
        code: 'EDIRECTORYOVERLAP',
        message: 'The schema and output directories must not be the same directory.',
      },
    ];
  }

  try {
    const stats = await Fs.stat(schemaDirectory);

    if (!stats.isDirectory()) {
      return [
        {
          code: 'ESCHEMADIRECTORY',
          message: `The schema path ${JSON.stringify(schemaDirectory)} is not a directory.`,
        },
      ];
    }
  } catch (error) {
    return [
      {
        code: 'ESCHEMADIRECTORY',
        message: `Unable to access schema directory ${JSON.stringify(
          schemaDirectory,
        )}: ${getErrorMessage(error)}`,
      },
    ];
  }

  return [];
}

async function loadSchemas(
  schemaDirectory: string,
  relativeSchemaPaths: string[],
): Promise<LoadedSchema[]> {
  const schemas: LoadedSchema[] = [];
  const issues: DirectoryGenerationIssue[] = [];

  for (const relativeSchemaPath of relativeSchemaPaths) {
    const schemaPath = Path.resolve(schemaDirectory, relativeSchemaPath);

    if (!relativeSchemaPath.endsWith('.json')) {
      issues.push({
        code: 'EEXTENSION',
        message: `Matched schema ${JSON.stringify(schemaPath)} does not end in .json.`,
        schemaPath,
      });
      continue;
    }

    try {
      const stats = await Fs.lstat(schemaPath);

      if (stats.isSymbolicLink()) {
        continue;
      }

      const source = await Fs.readFile(schemaPath, 'utf8');
      let schema: unknown;

      try {
        schema = JSON.parse(source);
      } catch (error) {
        issues.push({
          code: 'EINVALIDJSON',
          message: `Unable to parse schema ${JSON.stringify(schemaPath)}: ${getErrorMessage(error)}`,
          schemaPath,
        });
        continue;
      }

      if (!isSchemaRoot(schema)) {
        issues.push({
          code: 'ESCHEMAROOT',
          message: `Schema ${JSON.stringify(schemaPath)} must contain a JSON object or boolean.`,
          schemaPath,
        });
        continue;
      }

      schemas.push({
        schemaPath,
        relativeSchemaPath,
        schema,
        uri: pathToFileURL(schemaPath).href,
      });
    } catch (error) {
      issues.push({
        code: 'ESCHEMAREAD',
        message: `Unable to read schema ${JSON.stringify(schemaPath)}: ${getErrorMessage(error)}`,
        schemaPath,
      });
    }
  }

  if (issues.length) {
    throw new DirectoryGenerationError(issues);
  }

  if (!schemas.length) {
    throw new DirectoryGenerationError([
      {
        code: 'ENOMATCH',
        message: 'No non-symbolic-link schema files remained after discovery.',
      },
    ]);
  }

  return schemas;
}

function isSchemaRoot(value: unknown): value is JSONSchema7Definition {
  return (
    typeof value === 'boolean' ||
    (typeof value === 'object' && value !== null && !Array.isArray(value))
  );
}

function isPathWithin(relativePath: string) {
  const normalizedPath = toPosixPath(relativePath);

  return (
    !!normalizedPath &&
    normalizedPath !== '..' &&
    !normalizedPath.startsWith('../') &&
    !Path.posix.isAbsolute(normalizedPath) &&
    !Path.win32.isAbsolute(relativePath)
  );
}

function toPosixPath(value: string) {
  return value.replace(/\\/g, '/');
}

function diagnosticKey(diagnostic: IParserDiagnostic) {
  return [
    diagnostic.code,
    diagnostic.severity,
    diagnostic.uri,
    diagnostic.baseUri,
    diagnostic.message,
  ].join('\u0000');
}

function deduplicateIssues(issues: DirectoryGenerationIssue[]) {
  const uniqueIssues = new Map<string, DirectoryGenerationIssue>();

  for (const issue of issues) {
    const key = issue.diagnostic
      ? [issue.code, issue.diagnostic.baseUri].join('\u0000')
      : [issue.code, issue.schemaPath, issue.declarationPath, issue.message].join('\u0000');

    uniqueIssues.set(key, issue);
  }

  return [...uniqueIssues.values()];
}

function uriToSchemaPath(uri: string) {
  try {
    const url = new URL(uri);

    return url.protocol === 'file:' ? fileURLToPath(url) : undefined;
  } catch {
    return undefined;
  }
}

function getErrorMessage(error: unknown) {
  return error instanceof Error ? error.message : String(error);
}
